# Simplified to minimal working configuration
name: .NET Desktop CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        version: '9.0.x'

    - name: Build project
      run: dotnet build OmniDB.WinForms/OmniDB.WinForms.csproj --configuration Release
      working-directory: ${{ github.workspace }}